analyzer:
  skip_excluded: true

excludes:
  paths:
    - pattern: 'packages/package-b/**'
      reason: 'OPTIONAL_COMPONENT_OF'
      comment: 'Backend logic is excluded.'
  scopes:
    - pattern: 'devDependencies'
      reason: 'DEV_DEPENDENCY_OF'
      comment: 'Exclude development dependencies from analysis.'